version: '3.8'

services:
  AW98tang:
    # 使用 Docker Hub 镜像（如需本地构建，将 image 改为 build: .）
    image: awdress/aw98tang:latest
    
    # 容器名称
    container_name: AW98tang
    
    # 自动重启策略：除非手动停止，否则总是重启
    restart: unless-stopped
    
    # 端口映射：主机端口:容器端口
    ports:
      - "5000:5000"  # Web 控制面板端口（可自定义主机端口，如：15000:5000）
    
    # 数据卷挂载：将主机目录映射到容器内
    volumes:
      - ./AW98tang/config.json:/app/config.json  # 配置文件（必须）
      - ./AW98tang/logs:/app/logs                # 日志目录
      - ./AW98tang/debug:/app/debug              # 调试文件目录
      - ./AW98tang/data:/app/data                # 统计数据和登录状态目录（重要）
    
    # 环境变量配置
    environment:
      # Python 输出不缓冲，实时显示日志
      - PYTHONUNBUFFERED=1
      
      # 时区设置
      - TZ=Asia/Shanghai
      
      # Web 控制面板登录配置（建议修改默认密码）
      - WEB_USERNAME=${WEB_USERNAME:-admin}      # 默认用户名: admin
      - WEB_PASSWORD=${WEB_PASSWORD:-password}   # 默认密码: password
      
      # Git 自动更新配置（可选）
      - SKIP_GIT=true                                # 跳过Docker启动时的Git操作（推荐）
      # - GIT_REMOTE=https://github.com/AWdress/AW98tang.git  # 自定义仓库地址（默认AW98tang）
      # - GIT_BRANCH=main                              # 自定义分支（默认main）
      
      # GitHub Token配置（Web界面更新必需！）
      # 访问 https://github.com/settings/tokens 生成Token（勾选repo权限）
      # - GITHUB_TOKEN=ghp_YOUR_TOKEN_HERE             # 将ghp_YOUR_TOKEN_HERE替换为你的Token
      
      # Git 更新方案说明：
      # ✅ 推荐: SKIP_GIT=true + Web界面更新（需要配置GITHUB_TOKEN）
      # ❌ 不推荐: Docker启动时自动更新（容器内网络可能受限）
      
      # 代理配置（可选，如需使用代理请取消注释并填写）
      # - http_proxy=http://proxy.example.com:8080
      # - https_proxy=http://proxy.example.com:8080
      # - no_proxy=localhost,127.0.0.1
    
    # 网络配置
    networks:
      - sehuatang-net
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1G      # 最大内存使用 1GB
        reservations:
          memory: 512M    # 预留内存 512MB

# 网络定义
networks:
  sehuatang-net:
    driver: bridge  # 使用桥接网络
