version: '3.8'

services:
  AW98tang:
    image: awdress/aw98tang:latest
    container_name: AW98tang
    restart: unless-stopped
    
    ports:
      - "5000:5000"  # Web 控制面板端口（可自定义，如：15000:5000）
    
    volumes:
      - ./AW98tang/config.json:/app/config.json
      - ./AW98tang/logs:/app/logs
      - ./AW98tang/debug:/app/debug
      - ./AW98tang/data:/app/data
    
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      - WEB_USERNAME=${WEB_USERNAME:-admin}      # 默认: admin
      - WEB_PASSWORD=${WEB_PASSWORD:-password}   # 默认: password
      - STARTUP_AUTO_UPDATE=false                # 关闭启动时自动更新
    
    networks:
      - sehuatang-net
    
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  sehuatang-net:
    driver: bridge